pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "petchimuthu1995/cred_app"
    REGISTRY_CRED = "dockerhub-cred"
    KUBECONFIG = "kubeconfig-credentials"
  }

  stages {
    stage('Checkout Code') {
      steps {
         git branch: 'main',
        git url: 'https://github.com/Petchimuthu19/Jenkins_Projects.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          dockerImage = docker.build("${DOCKER_IMAGE}:${env.BUILD_NUMBER}")
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', REGISTRY_CRED) {
            dockerImage.push("${env.BUILD_NUMBER}")
            dockerImage.push("latest")
          }
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        withCredentials([file(credentialsId: "${KUBECONFIG}", variable: 'KUBECONFIG_FILE')]) {
          sh 'kubectl apply -f deployment.yaml'
          sh 'kubectl apply -f service.yaml'
        }
      }
    }
  }
}
